### ISSUE TITLE
Debug issue in bam_to_h5.R when running Edward's new S.cerevisiae FASTA and GFF

### ISSUE THREAD

**Issue by FlicAnderson** [riboviz/riboviz#171]
On 23rd April, noticed riboviz error when running new transcriptome annotations for S. cereviseae, new FASTA and GFF files. Was testing with full-size files from Brar et al 2012 (B-Sc_2012).

* vignette runs fine
* dry run is fine (6 samples, 0 failed)
* full run (6 samples) FAILS:  6 samples, 6 failed:
```console
# 23 Apr 2020
# B-Sc_2012, FULL RUN, 6 samples, updated .gff, updated .fasta (these pass check_fasta_gff.py)
# develop branch, last commit: 6324166
# 23 Apr 2020, started: 1636, ended: 
(base) flic@circe:~/riboviz$ time python -m riboviz.tools.prep_riboviz -c B-Sc_2012/B-Sc_2012_config.yaml
Running under Python: 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0]
Created by: RiboViz Date: 2020-04-23 16:36:29.836118 Command-line tool: /home/flic/riboviz/riboviz/tools/prep_riboviz.py File: /home/flic/riboviz/riboviz/tools/prep_riboviz.py Version: commit 63241663f2cf91fdac18a6ba1d5a80e3f47101dd date 2020-04-23 16:30:48+01:00 
Configuration file: B-Sc_2012/B-Sc_2012_config.yaml
Command file: run_riboviz_B-Sc_2012.sh
Number of processes: 8
Build indices for alignment, if necessary/requested
Build indices for alignment (B-Sc_2012/input/yeast_rRNA_R64-1-1.fa). Log: B-Sc_2012/logs/20200423-163629/hisat2_build_r_rna.log
Build indices for alignment (B-Sc_2012/input/verifiedORF_abundant_full-ORF_ypd_plus_other_fixed_UTR_length_transcripts_nointrons_issues_removed.fasta). Log: B-Sc_2012/logs/20200423-163629/hisat2_build_orf.log
Processing samples
Processing sample: PRE_ENTRY_1
Processing file: B-Sc_2012/input/SRR387873_GSM843749_footprints_for_the_A_timepoint_of_the_traditional_timecourse_premeiotic_Saccharomyces_cerevisiae_RNA-Seq.fastq.gz
Cut out sequencing library adapters. Log: B-Sc_2012/logs/20200423-163629/PRE_ENTRY_1/01_cutadapt.log
Remove rRNA or other contaminating reads by alignment to rRNA index files. Log: B-Sc_2012/logs/20200423-163629/PRE_ENTRY_1/02_hisat2_rrna.log
Align remaining reads to ORFs index files using hisat2. Log: B-Sc_2012/logs/20200423-163629/PRE_ENTRY_1/03_hisat2_orf.log
Trim 5' mismatches from reads and remove reads with more than 2 mismatches. Log: B-Sc_2012/logs/20200423-163629/PRE_ENTRY_1/04_trim_5p_mismatch.log
Convert SAM to BAM and sort on genome. Log: B-Sc_2012/logs/20200423-163629/PRE_ENTRY_1/05_samtools_view_sort.log
Index BAM file. Log: B-Sc_2012/logs/20200423-163629/PRE_ENTRY_1/06_samtools_index.log
Calculate transcriptome coverage for + strand and save as a bedgraph. Log: B-Sc_2012/logs/20200423-163629/PRE_ENTRY_1/07_bedtools_genome_cov_plus.log
Calculate transcriptome coverage for - strand and save as a bedgraph. Log: B-Sc_2012/logs/20200423-163629/PRE_ENTRY_1/08_bedtools_genome_cov_minus.log
Make length-sensitive alignments in H5 format. Log: B-Sc_2012/logs/20200423-163629/PRE_ENTRY_1/09_bam_to_h5.log
Problem processing sample: PRE_ENTRY_1
AssertionError
Traceback (most recent call last):
  File "/home/flic/riboviz/riboviz/tools/prep_riboviz.py", line 515, in process_samples
    sample_logs_dir, run_config)
  File "/home/flic/riboviz/riboviz/tools/prep_riboviz.py", line 430, in process_sample
    orf_gff_file, config, log_file, run_config)
  File "/home/flic/riboviz/riboviz/workflow.py", line 533, in bam_to_h5
    run_config.is_dry_run)
  File "/home/flic/riboviz/riboviz/process_utils.py", line 130, in run_logged_command
    run_command(cmd, f, f)
  File "/home/flic/riboviz/riboviz/process_utils.py", line 22, in run_command
    assert exit_code == 0, "%s failed with exit code %d" % (cmd, exit_code)
AssertionError: ['Rscript', '--vanilla', '/home/flic/riboviz/rscripts/bam_to_h5.R', '--num-processes=8', '--min-read-length=10', '--max-read-length=50', '--buffer=250', '--primary-id=Name', '--secondary-id=NULL', '--dataset=B-Sc_2012', '--bam-file=B-Sc_2012/output/PRE_ENTRY_1/PRE_ENTRY_1.bam', '--hd-file=B-Sc_2012/output/PRE_ENTRY_1/PRE_ENTRY_1.h5', '--orf-gff-file=B-Sc_2012/input/transcriptcentric_abundant_full-ORF_ypd_plus_other_fixed_UTR_length_transcripts_issues_removed.gff', '--is-riboviz-gff=True', '--stop-in-cds=False'] failed with exit code 1
Processing sample: PRE_ENTRY_2
# ... same error messages for other samples...
Make length-sensitive alignments in H5 format. Log: B-Sc_2012/logs/20200423-163629/META_II_2/09_bam_to_h5.log
Problem processing sample: META_II_2
AssertionError
Traceback (most recent call last):
  File "/home/flic/riboviz/riboviz/tools/prep_riboviz.py", line 515, in process_samples
    sample_logs_dir, run_config)
  File "/home/flic/riboviz/riboviz/tools/prep_riboviz.py", line 430, in process_sample
    orf_gff_file, config, log_file, run_config)
  File "/home/flic/riboviz/riboviz/workflow.py", line 533, in bam_to_h5
    run_config.is_dry_run)
  File "/home/flic/riboviz/riboviz/process_utils.py", line 130, in run_logged_command
    run_command(cmd, f, f)
  File "/home/flic/riboviz/riboviz/process_utils.py", line 22, in run_command
    assert exit_code == 0, "%s failed with exit code %d" % (cmd, exit_code)
AssertionError: ['Rscript', '--vanilla', '/home/flic/riboviz/rscripts/bam_to_h5.R', '--num-processes=8', '--min-read-length=10', '--max-read-length=50', '--buffer=250', '--primary-id=Name', '--secondary-id=NULL', '--dataset=B-Sc_2012', '--bam-file=B-Sc_2012/output/META_II_2/META_II_2.bam', '--hd-file=B-Sc_2012/output/META_II_2/META_II_2.h5', '--orf-gff-file=B-Sc_2012/input/transcriptcentric_abundant_full-ORF_ypd_plus_other_fixed_UTR_length_transcripts_issues_removed.gff', '--is-riboviz-gff=True', '--stop-in-cds=False'] failed with exit code 1
Finished processing 6 samples, 6 failed
Processing error: B-Sc_2012/B-Sc_2012_config.yaml
Exception
Traceback (most recent call last):
  File "/home/flic/riboviz/riboviz/tools/prep_riboviz.py", line 823, in prep_riboviz
    run_workflow(config_file, is_dry_run)
  File "/home/flic/riboviz/riboviz/tools/prep_riboviz.py", line 702, in run_workflow
    raise Exception("No samples were processed successfully")
Exception: No samples were processed successfully

real	13m22.078s
user	72m34.655s
sys	33m48.946s
# FAIL!
```
Error for one sample:
```
# error for 1 sample from riboviz*.log
2020-04-23 16:38:45,280:riboviz.workflow:INFO: Make length-sensitive alignments in H5 format. Log: B-Sc_2012/logs/20200423-163629/PRE_ENTRY_1/09_bam_to_h5.log
2020-04-23 16:38:49,770:__main__:ERROR: Problem processing sample: PRE_ENTRY_1
2020-04-23 16:38:49,770:__main__:ERROR: AssertionError
Traceback (most recent call last):
  File "/home/flic/riboviz/riboviz/tools/prep_riboviz.py", line 515, in process_samples
    sample_logs_dir, run_config)
  File "/home/flic/riboviz/riboviz/tools/prep_riboviz.py", line 430, in process_sample
    orf_gff_file, config, log_file, run_config)
  File "/home/flic/riboviz/riboviz/workflow.py", line 533, in bam_to_h5
    run_config.is_dry_run)
  File "/home/flic/riboviz/riboviz/process_utils.py", line 130, in run_logged_command
    run_command(cmd, f, f)
  File "/home/flic/riboviz/riboviz/process_utils.py", line 22, in run_command
    assert exit_code == 0, "%s failed with exit code %d" % (cmd, exit_code)
AssertionError: ['Rscript', '--vanilla', '/home/flic/riboviz/rscripts/bam_to_h5.R', '--num-processes=8', '--min-read-length=10', '--max-read-length=50', '--buffer=250', '--primary-id=Name', '--secondary-id=NULL', '--dataset=B-Sc_2012', '--bam-file=B-Sc_2012/output/PRE_ENTRY_1/PRE_ENTRY_1.bam', '--hd-file=B-Sc_2012/output/PRE_ENTRY_1/PRE_ENTRY_1.h5', '--orf-gff-file=B-Sc_2012/input/transcriptcentric_abundant_full-ORF_ypd_plus_other_fixed_UTR_length_transcripts_issues_removed.gff', '--is-riboviz-gff=True', '--stop-in-cds=False'] failed with exit code 1 
```
Investigation into bam_to_h5.R, since that's where the error happens:

NOTE: to debug this, it currently requires you to add the fix for interactive debugging #147 that we added to generate_stats_figs.R but which I don't think was added to bam_to_h5.R... 

```R
# threw in the interactive fix from regen-stats-32:

(base) flic@circe:~/riboviz$ R --vanilla --args --num-processes=8 --min-read-length=10 --max-read-length=50 --buffer=250 --primary-id=Name --secondary-id=NULL --dataset=B-Sc_2012 --bam-file=B-Sc_2012/output/PRE_ENTRY_1/PRE_ENTRY_1.bam --hd-file=B-Sc_2012/output/PRE_ENTRY_1/PRE_ENTRY_1.h5 --orf-gff-file=B-Sc_2012/input/transcriptcentric_abundant_full-ORF_ypd_plus_other_fixed_UTR_length_transcripts_issues_removed.gff --is-riboviz-gff=True --stop-in-cds=False

R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
 # ...other R startup chat...

> source("/home/flic/riboviz/rscripts/bam_to_h5.R")
[1] "Created by: RiboViz"
[1] "Date: 2020-04-23 17:17:17"
[1] "File: /home/flic/riboviz/rscripts/bam_to_h5.R"
[1] "Version: commit 63241663f2cf91fdac18a6ba1d5a80e3f47101dd date 2020-04-23 15:30:48"
The following object is masked _by_ .GlobalEnv:
    secondary_id
[1] "bam_to_h5.R running with parameters:"
Error: subscript contains invalid names

> traceback()
14: stop(wmsg(...), call. = FALSE)
13: .subscript_error("subscript contains invalid ", what)
12: NSBS(i, x, exact = exact, strict.upper.bound = !allow.append, 
        allow.NAs = allow.NAs)
11: NSBS(i, x, exact = exact, strict.upper.bound = !allow.append, 
        allow.NAs = allow.NAs)
10: normalizeSingleBracketSubscript(i, xstub)
9: extractCOLS(x, j)
8: extractCOLS(x, j)
7: mcols(gff)[primary_id]
6: mcols(gff)[primary_id]
5: unique(mcols(gff)[primary_id][, 1]) at bam_to_h5.R#218
4: eval(ei, envir)
3: eval(ei, envir)
2: withVisible(eval(ei, envir))
1: source("/home/flic/riboviz/rscripts/bam_to_h5.R")
```

So it's in there somewhere.. I tried running lines through separately to see if I could identify what was the problem in the script. 

```R
> reads_to_list <- function(gene_location, bam_file, read_range, left_flank,right_flank, mult_exon=TRUE)
+ {
+   # Computes matrix of read counts with starting position and read length
+   # on a signle gene whose co-ordinates are supplied as arguments
+   #  
+   # Args:
+   #   gene_location: (list) gff line containing gene co-ordinates
+   #   bam_file: (string) name of bam_file with reads in it
+   #   read_range: (int) vector of integer read lengths, e.g. 15:50 
+   #   flank: (int) width of flanking region to include outside gene body/CDS
+   #   mult_exon: If TRUE, uses only the first supplied exon for gene co-ordinates
+   #
+   # Returns:
+   #   output: matrix of integer counts for each row/start position and column/read length
+   #
+ 
+   if(!mult_exon)
+     # If the gene is a single exon gene but multiple GRanges specified,
+     # use the first GRange
+   { gene_location <- gene_location[1]
+   }
+   
+   # Number of read length categories
+   read_range_len <- length(read_range)
+ 
+   # Specify output matrix to store read data
+   gene_length = sum(sum(coverage(gene_location)))
+   output <- matrix(0,nrow=read_range_len,ncol=(gene_length + left_flank + right_flank))
+   
+ # If CDS is on negative strand
+   if(as.character(strand(gene_location)[1])=="-"){
+     tmp <- left_flank
+     left_flank <- right_flank
+     right_flank <- tmp
+   }
+   
+   # Expand genomic locations to include flanking region positions
+   if(length(gene_location)==1) 
+   {# For single exon genes
+     start(gene_location) <- start(gene_location) - left_flank
+     end(gene_location) <- end(gene_location) + right_flank
+   }else{
+     # For multiple exon genes
+     start(gene_location)[start(gene_location)==min(start(gene_location))] <- 
+         start(gene_location)[start(gene_location)==min(start(gene_location))] - left_flank
+     end(gene_location)[end(gene_location)==max(end(gene_location))] <- 
+         end(gene_location)[end(gene_location)==max(end(gene_location))] + right_flank
+   }
+   
+   # Specify variables to read in and create a parameter file for bam data
+   bam_what <- c("strand", "pos", "qwidth")
+   bam_param <- ScanBamParam(which = gene_location, what = bam_what)
+   
+   # Read in bam data
+   bam_data <- scanBam(bam_file, param=bam_param)
+   
+   # Subset reads that are on the same strand at the genomic location
+   read_strand <- unlist(lapply(bam_data,function(x) x$strand ))
+   read_location <- unlist(lapply(bam_data,function(x) x$pos ))[read_strand==as.factor(strand(gene_location)[1])]
+   read_width <- unlist(lapply(bam_data,function(x) x$qwid ))[read_strand==as.factor(strand(gene_location)[1])]
+   
+   # Column numbers based on genomic position
+   nucleotide_pos <- unlist(which(coverage(gene_location)[seqnames(gene_location)[1]]==1))
+   
+   # If the specified flanking regions of a gene end up outside the chromosome locations (<0)
+   # add pseudo columns with negative numbers
+   if(min(start(gene_location))<min(nucleotide_pos))
+   { nucleotide_pos <- c(min(start(gene_location)):0,nucleotide_pos)
+   }
+   
+   # Count reads whose 5' ends map to each nucleotide and save them in output matrix
+   if(all(strand(gene_location)=="+")){
+     # For genes on positive strands
+     j <- 1 # counter for output row
+     for(i in read_range){
+       read_loc_len_i <- read_location[read_width==i] # subset reads of a particular length 
+       count_reads_len_i <- table(factor(read_loc_len_i,levels=nucleotide_pos)) # count reads of a particular length 
+       output[j,] <- c(count_reads_len_i)
+       j <- j+1
+     } 
+   } 
+   
+   if(all(strand(gene_location)=="-")){
+     # For genes on negative strands
+     j <- 1 # counter for output row
+     for(i in read_range){
+       read_loc_len_i <- read_width[read_width==i]+read_location[read_width==i]-1 # subset reads of a particular length 
+       count_reads_len_i <- table(factor(read_loc_len_i,levels=nucleotide_pos)) # count reads of a particular length
+       output[j,] <- c(rev(count_reads_len_i))
+       j <- j+1
+     }
+   }
+   
+   # Return the output matrix
+   return(output);
+ }
> 
> print_provenance(path_to_this_script)
[1] "Created by: RiboViz"
[1] "Date: 2020-04-23 17:29:40"
[1] "File: /home/flic/riboviz/rscripts/bam_to_h5.R"
[1] "Version: commit 63241663f2cf91fdac18a6ba1d5a80e3f47101dd date 2020-04-23 15:30:48"
> if (opt$secondary_id == "NULL") {
+   # unquote NULL option in secondary_id
+   secondary_id <- NULL
+ }
> 
> attach(opt)
The following object is masked _by_ .GlobalEnv:

    secondary_id

The following objects are masked from opt (pos = 3):

    bam_file, buffer, dataset, hd_file, help, is_riboviz_gff,
    is_test_run, max_read_length, min_read_length, num_processes,
    orf_gff_file, primary_id, secondary_id, stop_in_cds

> 
> print("bam_to_h5.R running with parameters:")
[1] "bam_to_h5.R running with parameters:"
> opt
$num_processes
[1] 8

$min_read_length
[1] 10

$max_read_length
[1] 50

$buffer
[1] 250

$primary_id
[1] "Name"

$secondary_id
[1] "NULL"

$bam_file
[1] "B-Sc_2012/output/PRE_ENTRY_1/PRE_ENTRY_1.bam"

$hd_file
[1] "B-Sc_2012/output/PRE_ENTRY_1/PRE_ENTRY_1.h5"

$orf_gff_file
[1] "B-Sc_2012/input/transcriptcentric_abundant_full-ORF_ypd_plus_other_fixed_UTR_length_transcripts_issues_removed.gff"

$dataset
[1] "B-Sc_2012"

$stop_in_cds
[1] FALSE

$is_riboviz_gff
[1] TRUE

$is_test_run
[1] FALSE

$help
[1] FALSE

> 
> # Range of read lengths 
> read_range <- min_read_length:max_read_length
> 
> # Read in the positions of all exons/genes in GFF format and subset CDS locations
> gff <- readGFFAsGRanges(orf_gff_file)
> 
> if(!is_riboviz_gff){
+   gff <- gff[gff$type=="CDS"]
+ }
> 
> # Read in the list of genes
> genes <- unique(mcols(gff)[primary_id][,1])
Error: subscript contains invalid names

# HERE. 
```
So the issue is in the line `genes <- unique(mcols(gff)[primary_id][,1])`. at LINE 202.

Investigated some of the relevant-seeming variables:

```R
> primary_id
[1] "Name"

> str(gff)
Formal class 'GRanges' [package "GenomicRanges"] with 7 slots
  ..@ seqnames       :Formal class 'Rle' [package "S4Vectors"] with 4 slots
  .. .. ..@ values         : Factor w/ 5086 levels "YAL001C_tx0",..: 1 2 3 4 5 6 7 8 9 10 ...
  .. .. ..@ lengths        : int [1:5086] 3 3 3 3 3 3 3 3 3 3 ...
  .. .. ..@ elementMetadata: NULL
  .. .. ..@ metadata       : list()
  ..@ ranges         :Formal class 'IRanges' [package "IRanges"] with 6 slots
  .. .. ..@ start          : int [1:15258] 1 26 3509 1 26 3851 1 22 643 1 ...
  .. .. ..@ width          : int [1:15258] 25 3483 125 25 3825 125 21 621 221 62 ...
  .. .. ..@ NAMES          : NULL
  .. .. ..@ elementType    : chr "ANY"
  .. .. ..@ elementMetadata: NULL
  .. .. ..@ metadata       : list()
  ..@ strand         :Formal class 'Rle' [package "S4Vectors"] with 4 slots
  .. .. ..@ values         : Factor w/ 3 levels "+","-","*": 1
  .. .. ..@ lengths        : int 15258
  .. .. ..@ elementMetadata: NULL
  .. .. ..@ metadata       : list()
  ..@ seqinfo        :Formal class 'Seqinfo' [package "GenomeInfoDb"] with 4 slots
  .. .. ..@ seqnames   : chr [1:5086] "YAL001C_tx0" "YAL002W_tx0" "YAL003W_id526" "YAL005C_id123" ...
  .. .. ..@ seqlengths : int [1:5086] NA NA NA NA NA NA NA NA NA NA ...
  .. .. ..@ is_circular: logi [1:5086] NA NA NA NA NA NA ...
  .. .. ..@ genome     : chr [1:5086] NA NA NA NA ...
  ..@ elementMetadata:Formal class 'DataFrame' [package "S4Vectors"] with 6 slots
  .. .. ..@ rownames       : NULL
  .. .. ..@ nrows          : int 15258
  .. .. ..@ listData       :List of 5
  .. .. .. ..$ source: Factor w/ 1 level "yeastutrgff": 1 1 1 1 1 1 1 1 1 1 ...
  .. .. .. ..$ type  : Factor w/ 3 levels "five_prime_UTR",..: 1 2 3 1 2 3 1 2 3 1 ...
  .. .. .. ..$ score : num [1:15258] NA NA NA NA NA NA NA NA NA NA ...
  .. .. .. ..$ phase : int [1:15258] NA 0 NA NA 0 NA NA 0 NA NA ...
  .. .. .. ..$ ID    : chr [1:15258] "YAL001C_tx0_five_prime_UTR" "YAL001C_CDS" "YAL001C_tx0_three_prime_UTR" "YAL002W_tx0_five_prime_UTR" ...
  .. .. ..@ elementType    : chr "ANY"
  .. .. ..@ elementMetadata: NULL
  .. .. ..@ metadata       : list()
  ..@ elementType    : chr "ANY"
  ..@ metadata       : list()

> ?mcols
‘mcols(x, use.names=TRUE)’, ‘mcols(x) <- value’: Get or set the
          metadata columns.  If ‘use.names=TRUE’ and the metadata
          columns are not ‘NULL’, then the names of ‘x’ are propagated
          as the row names of the returned DataTable object.  When
          setting the metadata columns, the supplied value must be
          ‘NULL’ or a DataTable object holding element-wise metadata.
```
Does it have anything to do with the bit of code here in bam_to_h5.R about secondary_id?
```R
if (opt$secondary_id == "NULL") {
  # unquote NULL option in secondary_id
  secondary_id <- NULL
}
```
What is different when this script is running on the USUAL GFF/FASTA?

In the 09_bam_to_h5.logs it's not clear what's different since the code isn't particularly helpful.

Both have:

$primary_id [1] "Name"

$secondary_id [1] "NULL"

I realised why the "The following object is masked by .GlobalEnv: secondary_id" bit happens - it's because the script is referring to opt$secondary_id and doing stuff to it, BEFORE it does the attach, I think. Don't think that's relevant to this issue but might be nice to fix, especially if I'm removing `attach()` in #32 refactoring...

```R
# Read in commandline arguments
opt <- parse_args(OptionParser(option_list=option_list),
                  convert_hyphens_to_underscores=TRUE)

if (opt$secondary_id == "NULL") {          # <<<<<<<< THIS BIT HERE
  # unquote NULL option in secondary_id
  secondary_id <- NULL
}
attach(opt)                                # BEFORE THIS  

print("bam_to_h5.R running with parameters:")
opt                                        # AND DEFINITELY BEFORE THIS
```
So I'm going to have to do a step-through of the normal-gff/fasta data to compare what it gives before the break point with the new gff/fasta.

Perhaps the issue is that the GFF attribute the line `genes <- unique(mcols(gff)[primary_id][,1])` is looking for (ie `primary_id`) ISN'T "Name" in this particular new-GFF file? Is it perhaps something different?

That's the next step of investigating, I think? Check out differences between attributes in GFFs?  

Advice welcome!

**Comment by FlicAnderson** [comment]
This is possibly something I can advance in combination with (or more reasonably after!) resolving some of the GFF/FASTA format issues with [example-datasets/#10](https://github.com/riboviz/example-datasets/issues/10) Drosophila dataset, since that'll involve me getting a better working knowledge of examining GFFs and what riboviz expects.  

Also worth checking if I actually *did* remove `attach()` in the refactoring in #184 ... :cold_sweat:

**Comment by mikej888** [comment]
Commit 84cf1a1 of [refactor-bam-to-h5-61](https://github.com/riboviz/riboviz/tree/refactor-bam-to-h5-61) has refactored `bam_to_h5.R` to avoid the `attach`. It now does:

```
opt <- parse_args(OptionParser(option_list = option_list),
                  convert_hyphens_to_underscores = TRUE)
...
if (opt$secondary_id  ==  "NULL") {
  # Unquote NULL option.
  secondary_id <- NULL
}
BamToH5(opt$bam_file, opt$orf_gff_file, opt$feature,
        opt$min_read_length, opt$max_read_length,
        opt$buffer, opt$primary_id, secondary_id, opt$dataset,
        opt$stop_in_cds, opt$is_riboviz_gff, opt$hd_file,
        opt$num_processes)
```
This ensures that `secondary_id` is `NULL` and not `"NULL"`.

**Comment by mikej888** [comment]
> Perhaps the issue is that the GFF attribute the line genes <- unique(mcols(gff)[primary_id][,1]) is looking for (ie primary_id) ISN'T "Name" in this particular new-GFF file? Is it perhaps something different?

During #61 I also ran into
```
Error: subscript contains invalid names
```
and you're right. Consider the `bam_to_h5.R` test data in [refactor-bam-to-h5-61](https://github.com/riboviz/riboviz/tree/refactor-bam-to-h5-61):

```console
$ cat data/Mok-tinysim-gffsam/tiny_2genes_20utrs.gff3 
##gff-version 3
##ewallace - Edward.Wallace@ed.ac.uk
##date 2021-01-13
MAT	ewallace	UTR5	1	20	.	+	.	Name=MAT
MAT	ewallace	CDS	21	32	.	+	.	Name=MAT
MAT	ewallace	UTR3	33	52	.	+	.	Name=MAT
MIKE	ewallace	UTR5	1	20	.	+	.	Name=MIKE
MIKE	ewallace	CDS	21	35	.	+	.	Name=MIKE
MIKE	ewallace	UTR3	36	55	.	+	.	Name=MIKE
```
Run `bam_to_h5.R`:
```console
$ samtools view -S -b data/Mok-tinysim-gffsam/A.sam > A.bam
$ samtools index A.bam
$ Rscript --vanilla rscripts/bam_to_h5.R --num-processes=1 \
  --min-read-length=10 --max-read-length=50 --buffer=20 \
  --primary-id=Name --secondary-id=NULL --dataset=Mok-tinysim \
  --bam-file=A.bam --hd-file=A.h5 \
  --orf-gff-file=data/Mok-tinysim-gffsam/tiny_2genes_20utrs.gff3 \
  --is-riboviz-gff=true --stop-in-cds=false
...
$primary_id
[1] "Name"

$secondary_id
[1] "NULL"
...
[1] "Saving mapped reads in a H5 file"
[1] "bam_to_h5.R done"
$ rm A.h5
```
Set `primary_id` to `XXX` and rerun:
```console
$ Rscript --vanilla rscripts/bam_to_h5.R --num-processes=1 \
  --min-read-length=10 --max-read-length=50 --buffer=20 \
  --primary-id=XXX --secondary-id=NULL --dataset=Mok-tinysim \
  --bam-file=A.bam --hd-file=A.h5 \
  --orf-gff-file=data/Mok-tinysim-gffsam/tiny_2genes_20utrs.gff3 \
  --is-riboviz-gff=true --stop-in-cds=false
...
$primary_id
[1] "XXX"

$secondary_id
[1] "NULL"
...
Error: subscript contains invalid names
Execution halted
```
Copy GFF file:
```console
$ cp data/Mok-tinysim-gffsam/tiny_2genes_20utrs.gff3  xxx.gff3
```
Replace `Name` with `XXX` in `xxx.gff3`:
```console
$ cat xxx.gff3 
##gff-version 3
##ewallace - Edward.Wallace@ed.ac.uk
##date 2021-01-13
MAT	ewallace	UTR5	1	20	.	+	.	XXX=MAT
MAT	ewallace	CDS	21	32	.	+	.	XXX=MAT
MAT	ewallace	UTR3	33	52	.	+	.	XXX=MAT
MIKE	ewallace	UTR5	1	20	.	+	.	XXX=MIKE
MIKE	ewallace	CDS	21	35	.	+	.	XXX=MIKE
MIKE	ewallace	UTR3	36	55	.	+	.	XXX=MIKE
```
Run:
```console
$ Rscript --vanilla rscripts/bam_to_h5.R --num-processes=1 \
  --min-read-length=10 --max-read-length=50 --buffer=20 \
  --primary-id=XXX --secondary-id=NULL --dataset=Mok-tinysim \
  --bam-file=A.bam --hd-file=A.h5 \
  --orf-gff-file=xxx.gff3 \
  --is-riboviz-gff=true --stop-in-cds=false
...
$primary_id
[1] "XXX"

$secondary_id
[1] "NULL"
...
[1] "Saving mapped reads in a H5 file"
[1] "bam_to_h5.R done"
```
Success!
