### ISSUE TITLE
Memory requirements

### ISSUE THREAD

**Issue by jabard89** [riboviz/riboviz#179]
I recently started using riboviz to analyze some published ribosome profiling data. It worked very well, thank you very much for all of your work! Running the program on the University of Chicago cluster, I ran into an error which I believe was due to insufficient memory (increasing the requested memory for the job solved the issue). Would it be possible to document a suggested minimum memory? Maybe it could be roughly estimated from the size of the fastq?
```
2020-05-21 10:44:15,085:__main__:INFO: Running under Python: 3.7.0 (default, Aug 30 2018, 20:21:53) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
2020-05-21 10:44:16,846:__main__:INFO: Created by: RiboViz Date: 2020-05-21 10:44:16.675845 Command-line tool: /project2/dadrummond/jbard/Iserman_2020/riboviz/riboviz/tools/prep_riboviz.py File: /project2/dadrummond/jbard/Iserman_2020/riboviz/riboviz/tools/prep_riboviz.py Version: commit 0ecd69ec0786eaeee78c4ce0999f4a181c775044 date 2020-03-04 05:45:40-08:00 
2020-05-21 10:44:16,846:__main__:INFO: Configuration file: Iserman_footprints_test/Iserman_umi_config.yaml
2020-05-21 10:44:16,862:__main__:INFO: Command file: run_riboviz_simdata_umi.sh
2020-05-21 10:44:16,863:__main__:INFO: Number of processes: 1
2020-05-21 10:44:17,588:__main__:INFO: Build indices for alignment, if necessary/requested
2020-05-21 10:44:17,589:riboviz.workflow:INFO: Build indices for alignment (Iserman_footprints_test/input/yeast_rRNA_R64-1-1.fa). Log: Iserman_footprints_test/logs/20200521-104416/hisat2_build_r_rna.log
2020-05-21 10:44:19,802:riboviz.workflow:INFO: Build indices for alignment (Iserman_footprints_test/input/yeast_CDS_w_250utrs.fa). Log: Iserman_footprints_test/logs/20200521-104416/hisat2_build_orf.log
2020-05-21 10:44:33,648:__main__:INFO: Processing samples
2020-05-21 10:44:33,681:__main__:INFO: Processing sample: WT_30_1_foot
2020-05-21 10:44:33,682:__main__:INFO: Processing file: Iserman_footprints_test/input/WT_30_1.fastq.gz
2020-05-21 10:44:33,682:riboviz.workflow:INFO: Cut out sequencing library adapters. Log: Iserman_footprints_test/logs/20200521-104416/WT_30_1_foot/01_cutadapt.log
2020-05-21 10:52:16,634:riboviz.workflow:INFO: Extract barcodes and UMIs. Log: Iserman_footprints_test/logs/20200521-104416/WT_30_1_foot/02_umi_tools_extract.log
2020-05-21 11:09:03,026:riboviz.workflow:INFO: Remove rRNA or other contaminating reads by alignment to rRNA index files. Log: Iserman_footprints_test/logs/20200521-104416/WT_30_1_foot/03_hisat2_rrna.log
2020-05-21 11:16:07,400:riboviz.workflow:INFO: Align remaining reads to ORFs index files using hisat2. Log: Iserman_footprints_test/logs/20200521-104416/WT_30_1_foot/04_hisat2_orf.log
2020-05-21 11:20:33,129:riboviz.workflow:INFO: Trim 5' mismatches from reads and remove reads with more than 2 mismatches. Log: Iserman_footprints_test/logs/20200521-104416/WT_30_1_foot/05_trim_5p_mismatch.log
2020-05-21 11:21:24,496:riboviz.workflow:INFO: Convert SAM to BAM and sort on genome. Log: Iserman_footprints_test/logs/20200521-104416/WT_30_1_foot/06_samtools_view_sort.log
2020-05-21 11:24:53,710:riboviz.workflow:INFO: Index BAM file. Log: Iserman_footprints_test/logs/20200521-104416/WT_30_1_foot/07_samtools_index.log
2020-05-21 11:25:01,817:riboviz.workflow:INFO: Idenfity UMI groups. Log: Iserman_footprints_test/logs/20200521-104416/WT_30_1_foot/08_umi_tools_group.log
2020-05-21 11:33:11,387:riboviz.workflow:INFO: Deduplicate UMIs. Log: Iserman_footprints_test/logs/20200521-104416/WT_30_1_foot/09_umi_tools_dedup.log
2020-05-21 11:50:05,395:__main__:ERROR: Problem processing sample: WT_30_1_foot
2020-05-21 11:50:05,396:__main__:ERROR: AssertionError
Traceback (most recent call last):
  File "/project2/dadrummond/jbard/Iserman_2020/riboviz/riboviz/tools/prep_riboviz.py", line 515, in process_samples
    sample_logs_dir, run_config)
  File "/project2/dadrummond/jbard/Iserman_2020/riboviz/riboviz/tools/prep_riboviz.py", line 388, in process_sample
    log_file, run_config)
  File "/project2/dadrummond/jbard/Iserman_2020/riboviz/riboviz/workflow.py", line 442, in deduplicate_umis
    run_config.is_dry_run)
  File "/project2/dadrummond/jbard/Iserman_2020/riboviz/riboviz/process_utils.py", line 130, in run_logged_command
    run_command(cmd, f, f)
  File "/project2/dadrummond/jbard/Iserman_2020/riboviz/riboviz/process_utils.py", line 22, in run_command
    assert exit_code == 0, "%s failed with exit code %d" % (cmd, exit_code)
AssertionError: ['umi_tools', 'dedup', '-I', 'Iserman_footprints_test/tmp/WT_30_1_foot/pre_dedup.bam', '-S', 'Iserman_footprints_test/output/WT_30_1_foot/WT_30_1_foot.bam', '--output-stats=Iserman_footprints_test/tmp/WT_30_1_foot/dedup_stats'] failed with exit code -7
2020-05-21 11:50:05,463:__main__:INFO: Finished processing 1 samples, 1 failed
2020-05-21 11:50:05,464:__main__:ERROR: Processing error: Iserman_footprints_test/Iserman_umi_config.yaml
2020-05-21 11:50:05,464:__main__:ERROR: Exception
Traceback (most recent call last):
  File "/project2/dadrummond/jbard/Iserman_2020/riboviz/riboviz/tools/prep_riboviz.py", line 823, in prep_riboviz
    run_workflow(config_file, is_dry_run)
  File "/project2/dadrummond/jbard/Iserman_2020/riboviz/riboviz/tools/prep_riboviz.py", line 702, in run_workflow
    raise Exception("No samples were processed successfully")
Exception: No samples were processed successfully
```

**Comment by mikej888** [comment]
@jabard, thanks that's a good suggestion. Even if it's not possible to roughly calculate it from the FASTQ file, evolving a set of guidelines would be a useful addition to the documentation.

I run RiboViz within an Ubuntu VM with 8GB which works fine for the "vignette" example in RiboViz. But to get an idea as to the scale of your data, please could you give:

* An indication as to the original memory you had.
* What you increased it to.
* The size of your FASTQ file.
* The size of Iserman_footprints_test/tmp/WT_30_1_foot/pre_dedup.bam which was passed into umi_tools.

Also, for future reference, there should have been a corresponding  Iserman_footprints_test/logs/WT_30_1_foot/09_umi_tools_dedup.log file for the umi_tools invocation which might have more information on why it failed.

For this specific issue, in looking for UMI-Tools exit codes (and what -7 might signify), I found "excessive dedup memory usage with output-stats" CGATOxford/UMI-tools/issues/409, so the problem may have arisen by our use of `--output-stats` by default which suggests that whether or not this is invoked should be a RiboViz configuration parameter.

**Comment by mikej888** [comment]
For 2.0 we will update documentation to say that memory usage may be an issue.

**Comment by kavousan** [comment]
Response from @amandamok:

> Our lab server has 62 GB and 40 cores. I ran Riboviz on the server with a dataset ~3G (gzipped fastq file) without issue.

**Comment by FlicAnderson** [comment]
@ewallace I think this is the same issue you've had with the Neurospora crassa dataset?

**Comment by ewallace** [comment]
Just noticed this old issue, did @canuse's work address this already?

**Comment by canuse** [comment]
I actually didn't do to much on the memory part, because I find out that in most conditions (unless you are running with a sample bigger than 20GB), the memory usage is less than 6GB per core per sample, which means that most eddie nodes can run it.
Some figures may be useful at issue #325 , which shows the peak memory vs different sample size, gff3 file items and cores. Bascally, the memory is proportional to sample_size, gff_size and num_process.

One of the main cause of OOM I meet is that we should add the peak memory usage of different sample together. For example, if I am running a dataset with 2 samples, and set numprocess to 4, then we will need either:
1. 8 cores, 6 GB memory each core, or
2. 4 cores, 12 GB memory each core, or
3. some other combination that have more than 48GB memory in total

If I run it on a 4 core 6GB/core environment, then a OOM is likely to happen
