### ISSUE TITLE
Error from generate_stats_figs during test run of Weinberg dataset 

### ISSUE THREAD

**Issue by 3mma-mack** [riboviz/riboviz#277]
Encountered error running testing the Weinberg et al 2016 dataset on Eddie in both nextflow and python during the  `generate_stats_figs` step. 
The dry run completed without issue but an `Assertionerror` was encountered when run with a sample dataset, and in the log the error appeared to be due to `Faceting variables must have at least one value`, as shown in the logs below. My first thought was that the problem was with the `count_threshold` as it is a smaller sample dataset, however this was already set to 1.

```
Running under Python: 3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:57:50)
[GCC 7.5.0]
Created by: RiboViz Date: 2021-01-29 11:50:19.160011 Command-line tool: /exports/eddie/scratch/s1734289/riboviz/riboviz/r$
Configuration file: W_Sc_2016/Weinberg_2016_RPF_3_samples_CDS_w_250utrs_config.yaml
Command file: run_riboviz_W-Sc_2016.sh
Number of processes: 2
Build indices for alignment, if necessary/requested
Build indices for alignment (../../riboviz/example-datasets/fungi/saccharomyces/contaminants/Saccharomyces_cerevi$
Build indices for alignment (../../riboviz/example-datasets/fungi/saccharomyces/annotation/Saccharomyces_cerevisi$
Processing samples
Processing sample: Cerevisiae_RPF
Processing file: W_Sc_2016/input/subset.fastq.gz
Cut out sequencing library adapters. Log: W_Sc_2016/logs/20210129-115019/Cerevisiae_RPF/01_cutadapt.log
Extract barcodes and UMIs. Log: W_Sc_2016/logs/20210129-115019/Cerevisiae_RPF/02_umi_tools_extract.log
Remove rRNA or other contaminating reads by alignment to rRNA index files. Log: W_Sc_2016/logs/20210129-115019/Ce$
Align remaining reads to ORFs index files using hisat2. Log: W_Sc_2016/logs/20210129-115019/Cerevisiae_RPF/04_his$
Trim 5' mismatches from reads and remove reads with more than 2 mismatches. Log: W_Sc_2016/logs/20210129-115019/C$
Convert SAM to BAM and sort on genome. Log: W_Sc_2016/logs/20210129-115019/Cerevisiae_RPF/06_samtools_view_sort.l$
Index BAM file. Log: W_Sc_2016/logs/20210129-115019/Cerevisiae_RPF/07_samtools_index.log
Calculate transcriptome coverage for + strand and save as a bedgraph. Log: W_Sc_2016/logs/20210129-115019/Cerevis$
Calculate transcriptome coverage for - strand and save as a bedgraph. Log: W_Sc_2016/logs/20210129-115019/Cerevis$
Make length-sensitive alignments in H5 format. Log: W_Sc_2016/logs/20210129-115019/Cerevisiae_RPF/10_bam_to_h5.log
Create summary statistics, and analyses and QC plots for both RPF and mRNA datasets. Log: W_Sc_2016/logs/20210129$
ERROR: Problem processing sample: Cerevisiae_RPF
ERROR: AssertionError
Traceback (most recent call last):
  File "/exports/eddie/scratch/s1734289/riboviz/riboviz/riboviz/tools/prep_riboviz.py", line 524, in process_samples
    sample_logs_dir, run_config)
  File "/exports/eddie/scratch/s1734289/riboviz/riboviz/riboviz/tools/prep_riboviz.py", line 446, in process_sample
    config, log_file, run_config)
  File "/exports/eddie/scratch/s1734289/riboviz/riboviz/riboviz/workflow.py", line 595, in generate_stats_figs
    run_config.is_dry_run)
  File "/exports/eddie/scratch/s1734289/riboviz/riboviz/riboviz/process_utils.py", line 130, in run_logged_command
    run_command(cmd, f, f)
  File "/exports/eddie/scratch/s1734289/riboviz/riboviz/riboviz/process_utils.py", line 22, in run_command
    assert exit_code == 0, "%s failed with exit code %d" % (cmd, exit_code)
AssertionError: ['Rscript', '--vanilla', '/exports/eddie/scratch/s1734289/riboviz/riboviz/rscripts/generate_stats_figs.R', '--num-processes=2', '--min-read-leng$
Finished processing 1 samples, 1 failed
ERROR: Processing error: W_Sc_2016/Weinberg_2016_RPF_3_samples_CDS_w_250utrs_config.yaml
Exception
Traceback (most recent call last):
  File "/exports/eddie/scratch/s1734289/riboviz/riboviz/riboviz/tools/prep_riboviz.py", line 832, in prep_riboviz
    run_workflow(config_file, is_dry_run)
  File "/exports/eddie/scratch/s1734289/riboviz/riboviz/riboviz/tools/prep_riboviz.py", line 711, in run_workflow
    raise Exception("No samples were processed successfully")
Exception: No samples were processed successfully

```
As the error occurred during generate_stats_figs I went into the logs and found the error `Faceting variables must have at least one value ` in both the python and nextflow logs.

```
[1] "Created by: RiboViz"
[1] "Date: 2021-01-29 12:04:04"
[1] "File: /exports/eddie/scratch/s1734289/riboviz/riboviz/rscripts/generate_stats_figs.R"
[1] "Version: commit 3e3cd2f1a9f4843170304c596149bbeb8c4e9549 date 2021-01-06 09:46:48 GMT"
[1] "generate_stats_figs.R running with parameters:"
$output_dir
[1] "W_Sc_2016/output/Cerevisiae_RPF"

$orf_fasta_file
[1] "../../riboviz/example-datasets/fungi/saccharomyces/annotation/Saccharomyces_cerevisiae_yeast_CDS_w_250utrs.fa"

$orf_gff_file
[1] "../../riboviz/example-datasets/fungi/saccharomyces/annotation/Saccharomyces_cerevisiae_yeast_CDS_w_250utrs.gff3"

$num_processes
[1] 2

$min_read_length
[1] 10

$max_read_length
[1] 50

$buffer
[1] 250

$primary_id
[1] "Name"

$dataset
[1] "W_Sc_2016"

$rpf
[1] TRUE

$features_file
[1] "data/yeast_features.tsv"

$do_pos_sp_nt_freq
[1] TRUE

$t_rna_file
[1] "data/yeast_tRNAs.tsv"

$codon_positions_file
[1] "data/yeast_codon_pos_i200.RData"

$count_threshold
[1] 1

$length_threshold
[1] 500

$output_prefix
[1] ""

$hd_file
[1] "W_Sc_2016/output/Cerevisiae_RPF/Cerevisiae_RPF.h5"

$nnt_buffer
[1] 25

$nnt_gene
[1] 50

$asite_disp_length_file
[1] "data/yeast_standard_asite_disp_length.txt"

$help
[1] FALSE

[1] "Starting: Check for 3nt periodicity globally"
`summarise()` ungrouping output (override with `.groups` argument)
`summarise()` ungrouping output (override with `.groups` argument)
Saving 7 x 7 in image
[1] "Completed: Check for 3nt periodicity globally"
Warning message:
In write.table(three_nucleotide_periodicity_data, file = tsv_file_path,  :
  appending column names to file
[1] "Starting: Distribution of lengths of all mapped reads"
Saving 7 x 7 in image
[1] "Completed: Distribution of lengths of all mapped reads"
Warning message:
In write.table(read_length_data, file = tsv_file_path, append = T,  :
  appending column names to file
[1] "Starting: Biases in nucleotide composition along mapped read lengths"
1] "finished for loop"
[1] "finished prepping Length, Position, Frame variables"
[1] "finished, returning all_out"
[1] "Completed: Biases in nucleotide composition along mapped read lengths"
Warning message:
In write.table(all_out, file = tsv_file_path, append = T, sep = "\t",  :
  appending column names to file
[1] "Starting: Check for 3nt periodicity (frame) by gene"
Parsed with column specification:
cols(
  read_length = col_double(),
  asite_displacement = col_double()
)
Note: Using an external vector in selections is ambiguous.
ℹ Use `all_of(feat_names)` instead of `feat_names` to silence this message.
ℹ See <https://tidyselect.r-lib.org/reference/faq-external-vector.html>.
This message is displayed once per session.
[1] "Completed: Check for 3nt periodicity (frame) by Gene"
Warning message:
In write.table(gene_read_frames_data, file = tsv_file_path, append = T,  :
  appending column names to file
[1] "Starting: Position specific distribution of reads"
Saving 7 x 7 in image
Warning messages:
1: Removed 1000 row(s) containing missing values (geom_path).
2: In write.table(pos_sp_rpf_norm_reads_data, file = tsv_file_path,  :
  appending column names to file
[1] "Completed: Position specific distribution of reads - RPF method"
[1] "Completed: Position specific distribution of reads"
[1] "Starting: Calculate TPMs of genes"
[1] "Completed: Calculate TPMs of genes"
Warning message:
In write.table(tpms, file = tsv_file_path, append = T, sep = "\t",  :
  appending column names to file
[1] "Starting: Correlations between TPMs of genes with their sequence-based features"
Saving 7 x 7 in image
Error: Faceting variables must have at least one value
Backtrace:
     █
  1. └─global::WriteSequenceBasedFeatures(features_plot)
  2.   └─ggplot2::ggsave(...)
  3.     ├─grid::grid.draw(plot)
  4.     └─ggplot2:::grid.draw.ggplot(plot)
  5.       ├─base::print(x)
  6.       └─ggplot2:::print.ggplot(x)
  7.         ├─ggplot2::ggplot_build(x)
  8.         └─ggplot2:::ggplot_build.ggplot(x)
  9.           └─layout$setup(data, plot$data, plot$plot_env)
 10.             └─ggplot2:::f(..., self = self)
 11.               └─self$facet$compute_layout(data, self$facet_params)
 12.                 └─ggplot2:::f(...)
 13.                   ├─ggplot2:::unrowname(...)
 14.                   │ └─base::is.data.frame(x)
 15.                   └─ggplot2::combine_vars(data, params$plot_env, vars, drop = params$drop)
Execution halted

```
This was run on an interactive node on Eddie on the master branch of riboviz using 16G of memory. My only idea at the moment is it could be due to the method of sampling I used, as sampling the fastq.gz file with `head` produced truncated reads so I created my subset file using `zcat SRR1049521.fastq.gz | awk '(NR<=40000)' > subset.fastq.gz`, however having checked the file the reads do seem to be in the expected format. 

Additionally, the only output files that have not been produced are codon_ribodens.tsv and pdf files, as well as the TMPs_collated.tsv and read_counts.tsv, which all come after 'Correlations between TPMs of genes with their sequence-based features' in the pipeline. The rest of the output files are there as expected.

Any advice would be appreciated!

**Comment by ewallace** [comment]
Discussed 5th Feb with @3mma-mack and @swinterbourne. We had some suggestions for troubleshooting:

1. Attempt to run on full-size dataset, in case this is an artefact of downsampling. Or at least run on more reads. We checked the [Sequence Read Archive page](https://www.ncbi.nlm.nih.gov/sra?term=SRX391790) which has 102Mi spots (we think, 102Mi reads) - perhaps running 1Mi through is a better try?
2. Also could try random downsampling `subsample_bioseqfile.py`, currently on branch `subsample-fastq-38` and described in pull request #234 . Documentation is in [subsample_bioseqfile.py](https://github.com/riboviz/riboviz/blob/subsample-fastq-38/riboviz/tools/subsample_bioseqfile.py).
3. Closer inspection of the files that were produced and how big they are. Especially, how many reads are in the bam file? And the summary figures of read counts by length.
4. Try interactive debugging `generate_stats_figs.R`, using the [R debugging suggestions](https://github.com/riboviz/riboviz/blob/develop/docs/developer/debugging.md#debugging-r-scripts-with-appropriate-command-line-arguments)

**Comment by 3mma-mack** [comment]
Here are the output files from the Weinberg run using the python workflow

```
-rw-r--r-- 1 s1734289 eddie_users 115K Feb  5 16:49 3ntframe_bygene.tsv
-rw-r--r-- 1 s1734289 eddie_users 4.3K Feb  5 16:49 3ntframe_propbygene.pdf
-rw-r--r-- 1 s1734289 eddie_users 5.5K Feb  5 15:51 3nt_periodicity.pdf
-rw-r--r-- 1 s1734289 eddie_users 1.5K Feb  5 15:51 3nt_periodicity.tsv
-rw-r--r-- 1 s1734289 eddie_users  59K Feb  5 15:22 Cerevisiae_RPF.bam
-rw-r--r-- 1 s1734289 eddie_users  46K Feb  5 15:22 Cerevisiae_RPF.bam.bai
-rw-r--r-- 1 s1734289 eddie_users  49M Feb  5 15:46 Cerevisiae_RPF.h5
-rw-r--r-- 1 s1734289 eddie_users 3.8K Feb  5 16:55 features.pdf
-rw-r--r-- 1 s1734289 eddie_users  97K Feb  5 15:22 minus.bedgraph
-rw-r--r-- 1 s1734289 eddie_users  97K Feb  5 15:22 plus.bedgraph
-rw-r--r-- 1 s1734289 eddie_users  57K Feb  5 16:47 pos_sp_nt_freq.tsv
-rw-r--r-- 1 s1734289 eddie_users 4.6K Feb  5 16:50 pos_sp_rpf_norm_reads.pdf
-rw-r--r-- 1 s1734289 eddie_users  14K Feb  5 16:50 pos_sp_rpf_norm_reads.tsv
-rw-r--r-- 1 s1734289 eddie_users 4.7K Feb  5 15:52 read_lengths.pdf
-rw-r--r-- 1 s1734289 eddie_users  444 Feb  5 15:52 read_lengths.tsv
-rw-r--r-- 1 s1734289 eddie_users 7.0K Feb  5 15:51 startcodon_ribogridbar.pdf
-rw-r--r-- 1 s1734289 eddie_users  14K Feb  5 15:51 startcodon_ribogrid.pdf
-rw-r--r-- 1 s1734289 eddie_users  86K Feb  5 16:52 tpms.tsv

```
Upon closer inspection the read counts by length and tpms files both contain 0 reads for all lengths and for all genes. The bam and H5 files are not empty but I think I need to get the files off of eddie to get them into a readable format. For now I am going to start a run with a file subsampled using `subsample_bioseqfile.py`. I have copied the above files to another directory for now.

**Comment by 3mma-mack** [comment]
Following the power cut all runs with the Weinberg dataset were producing errors at `cutadapt` , even those the subsampled datasets that had previously run to generate_stats_figs, so I deleted thw W_Sc_2016 folder and everything inside. Having redownloaded the input files and edited the config file from the version that can be found in example-datasets on branch weinberg-2016_dataset-20. I set the count_threshold to 1 as I had been using a smaller dataset, dedup_stats and dedup_umis were set to false as these were causing problems with umi_tools_deduplication previously, and num_processes set to 2 as this had been causing issues with memory prior to moving to eddie. 

Using the newly downloaded full dataset the process was rerun using python and also failed at `Starting: Correlations between TPMs of genes with their sequence-based features`, with the same error as described above. Looking at the output files of the run showed that the files produced were the same as those produced by the subsampled file in size, and both read_counts_by_length.tsv and tpms.tsv files contain 0 reads.
 
```
Cerevisiae_RPF]$ ls -l -h
total 51M
-rw-r--r-- 1 s1734289 eddie_users 115K Feb 10 20:01 3ntframe_bygene.tsv
-rw-r--r-- 1 s1734289 eddie_users 4.3K Feb 10 20:01 3ntframe_propbygene.pdf
-rw-r--r-- 1 s1734289 eddie_users 5.5K Feb 10 19:33 3nt_periodicity.pdf
-rw-r--r-- 1 s1734289 eddie_users 1.5K Feb 10 19:33 3nt_periodicity.tsv
-rw-r--r-- 1 s1734289 eddie_users  59K Feb 10 19:16 Cerevisiae_RPF.bam
-rw-r--r-- 1 s1734289 eddie_users  46K Feb 10 19:16 Cerevisiae_RPF.bam.bai
-rw-r--r-- 1 s1734289 eddie_users  49M Feb 10 19:30 Cerevisiae_RPF.h5
-rw-r--r-- 1 s1734289 eddie_users 3.8K Feb 10 20:04 features.pdf
-rw-r--r-- 1 s1734289 eddie_users  97K Feb 10 19:16 minus.bedgraph
-rw-r--r-- 1 s1734289 eddie_users  97K Feb 10 19:16 plus.bedgraph
-rw-r--r-- 1 s1734289 eddie_users  57K Feb 10 20:00 pos_sp_nt_freq.tsv
-rw-r--r-- 1 s1734289 eddie_users 4.6K Feb 10 20:01 pos_sp_rpf_norm_reads.pdf
-rw-r--r-- 1 s1734289 eddie_users  14K Feb 10 20:01 pos_sp_rpf_norm_reads.tsv
-rw-r--r-- 1 s1734289 eddie_users 4.7K Feb 10 19:33 read_lengths.pdf
-rw-r--r-- 1 s1734289 eddie_users  444 Feb 10 19:33 read_lengths.tsv
-rw-r--r-- 1 s1734289 eddie_users 7.0K Feb 10 19:33 startcodon_ribogridbar.pdf
-rw-r--r-- 1 s1734289 eddie_users  14K Feb 10 19:33 startcodon_ribogrid.pdf
-rw-r--r-- 1 s1734289 eddie_users  86K Feb 10 20:03 tpms.tsv
```
@ewallace mentioned that there may be an option in the config.yaml that may skip the `Starting: Correlations between TPMs of genes with their sequence-based features` step so I am going attempt a run with this option tonight and if that fails then I'm going to try interactive debugging, which will be slow as I have never tried to do it before.

**Comment by 3mma-mack** [comment]
Yesterday I changed `feature_file` to NULL in the config file, meaning that the step `Starting: Correlations between TPMs of genes with their sequence-based features` would be skipped. This lead to the run completing successfully, however once again `read_counts_by_length.tsv` and `tpms.tsv` files contained 0 reads. 

```
-rw-r--r-- 1 s1734289 eddie_users 115K Feb 11 17:44 3ntframe_bygene.tsv
-rw-r--r-- 1 s1734289 eddie_users 4.3K Feb 11 17:44 3ntframe_propbygene.pdf
-rw-r--r-- 1 s1734289 eddie_users 5.5K Feb 11 16:33 3nt_periodicity.pdf
-rw-r--r-- 1 s1734289 eddie_users 1.5K Feb 11 16:33 3nt_periodicity.tsv
-rw-r--r-- 1 s1734289 eddie_users  59K Feb 11 15:56 Cerevisiae_RPF.bam
-rw-r--r-- 1 s1734289 eddie_users  46K Feb 11 15:56 Cerevisiae_RPF.bam.bai
-rw-r--r-- 1 s1734289 eddie_users  49M Feb 11 16:27 Cerevisiae_RPF.h5
-rw-r--r-- 1 s1734289 eddie_users 5.7K Feb 11 17:50 codon_ribodens.pdf
-rw-r--r-- 1 s1734289 eddie_users 2.8K Feb 11 17:50 codon_ribodens.tsv
-rw-r--r-- 1 s1734289 eddie_users 3.8K Feb 10 20:04 features.pdf
-rw-r--r-- 1 s1734289 eddie_users  97K Feb 11 15:56 minus.bedgraph
-rw-r--r-- 1 s1734289 eddie_users  97K Feb 11 15:56 plus.bedgraph
-rw-r--r-- 1 s1734289 eddie_users  57K Feb 11 17:43 pos_sp_nt_freq.tsv
-rw-r--r-- 1 s1734289 eddie_users 4.6K Feb 11 17:46 pos_sp_rpf_norm_reads.pdf
-rw-r--r-- 1 s1734289 eddie_users  14K Feb 11 17:46 pos_sp_rpf_norm_reads.tsv
-rw-r--r-- 1 s1734289 eddie_users 4.7K Feb 11 16:34 read_lengths.pdf
-rw-r--r-- 1 s1734289 eddie_users  444 Feb 11 16:34 read_lengths.tsv
-rw-r--r-- 1 s1734289 eddie_users 7.0K Feb 11 16:33 startcodon_ribogridbar.pdf
-rw-r--r-- 1 s1734289 eddie_users  14K Feb 11 16:33 startcodon_ribogrid.pdf
-rw-r--r-- 1 s1734289 eddie_users  86K Feb 11 17:49 tpms.tsv
```
Meaning that the graphs produced contained no information. For example: [3nt_periodicity.pdf](https://github.com/riboviz/riboviz/files/5971096/3nt_periodicity.pdf)
[codon_ribodens.pdf](https://github.com/riboviz/riboviz/files/5971113/codon_ribodens.pdf)

@FlicAnderson has done some investigating and found a problem with our UMI regular expression which was previously `^(?P<umi_1>.{8})$` causing the program to look for UMIs at both ends of the strands, which impacted `umi_tools_dedup` and likely had a knock on effect the rest of the pipeline. She has corrected this to `(?P<umi_1>.{8})` and ran the Weinberg dataset successfully. I am repeating the run with the changes to double check that it works for me as well.

**Comment by ewallace** [comment]
So this error was caused by having no aligned reads. Do we need to have some obvious error message if there are few to no reads? Perhaps in `bam_to_h5.R`, which is the next file that sees the bam output?

Let's discuss next dev meeting with @mikej888 and @FlicAnderson as well.

**Comment by mikej888** [comment]
> So this error was caused by having no aligned reads. Do we need to have some obvious error message if there are few to no reads? Perhaps in `bam_to_h5.R`, which is the next file that sees the bam output?
> 
> Let's discuss next dev meeting with @mikej888 and @FlicAnderson as well.

Relates to #61.

**Comment by 3mma-mack** [comment]
Following discussion at the meeting, this error has been solved due fixing the regular expression for the UMIs and another issue ticket will be made for adding a warning in bam_to_h5 for if there are no reads present
