### ISSUE TITLE
cutadapt 3.x from `conda` causes workflow failure

### ISSUE THREAD

**Issue by mikej888** [riboviz/riboviz#380]
At yesterday's workshop dry-run, an attendee got an error when running the workflow:

```
Traceback (most recent call last):  
File "/.../miniconda3/envs/riboviz/bin/cutadapt", line 12, in <module>
    sys.exit(main())TypeError: main() missing 1 required positional argument: 'cmdlineargs'
- cutAdapters (WTnone)
  cutadapt --trim-n -O 1 -m 5 -a CTGTAGGCACC             -o trim.fq SRR1042855_s1mi.fastq.gz -j 0
-  Traceback (most recent call last):  File "/.../miniconda3/envs/riboviz/bin/cutadapt", line 12, in <module>
    sys.exit(main())TypeError: main() missing 1 required positional argument: 'cmdlineargs'
```

The version of cutadapt we use is 1.18. This is the default provided if running:
```console
$ conda install -y -c bioconda cutadapt
```
The attendee had 3.2. His fix was to run the above and force a reinstall i.e.
```console
$ conda install -c bioconda cutadapt --force-reinstall
```

**Comment by mikej888** [comment]
We could document this until such a time as we decide whether to upgrade to a more recent version of `cutadapt` (which also requires changing our install docs with the commands required to install a more recent version. This relates to, and overlaps with, #340, #390, #291.

**Comment by mikej888** [comment]
I tried to force an install of cutadapt 3.4 in my Ubuntu 18.04.5 VM:
```console
$ conda create --name riboviz-cut --clone riboviz
$ conda activate riboviz-cut
$ cutadapt --version
1.18
$ conda install -y -c bioconda cutadapt=3.4
...
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package __glibc conflicts for:
@/linux-64::__glibc==2.27=0
cutadapt=3.4 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
@|@/linux-64::__glibc==2.27=0
...
```
Try with Ubuntu 20.04.2 VM:
```console
$ conda install -y -c bioconda cutadapt=3.4

Package python conflicts for:
defaults|defaults/linux-64::python==3.7.6=h0371630_2
defaults/linux-64::python==3.7.6=h0371630_2The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - cutadapt=3.4 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - defaults/linux-64::python==3.7.6=h0371630_2 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.31
```

Try `pip install`:

```console
$ pip install --user --upgrade cutadapt
$ cutadapt --version
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/riboviz-cut/bin/cutadapt", line 12, in <module>
    sys.exit(main())
TypeError: main() missing 1 required positional argument: 'cmdlineargs'
$ cat /home/ubuntu/miniconda3/envs/riboviz-cut/bin/cutadapt 
#!/bin/sh
'''exec' /home/ubuntu/miniconda3/envs/riboviz-cut/bin/python "$0" "$@"
' '''
# -*- coding: utf-8 -*-
import re
import sys

from cutadapt.__main__ import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```
For cutadapt 1.18, this file is the same, so the problem lies elsewhere.

**Comment by mikej888** [comment]
Using `pip` installed version 3.4 which then ran without complaint:
```console
$ conda remove cutadapt
$ pip install cutadapt
$ cutadapt --version
3.4
```

**Comment by mikej888** [comment]
I tried `pip`, erroneously adding `--user` which didn't install `cutadapt` within my conda environment, but meant it was still usable:
```console
$ pip install --user --upgrade cutadapt
```
This gave:
```console
$ cutadapt --version
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/riboviz-cut/bin/cutadapt", line 12, in <module>
    sys.exit(main())
TypeError: main() missing 1 required positional argument: 'cmdlineargs'
```

I ran an interactive Python session to mimic the content of `/home/ubuntu/miniconda3/envs/riboviz-cut/bin/cutadapt`:

```python
from cutadapt.__main__ import main
main()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: main() missing 1 required positional argument: 'cmdlineargs'
```

I ran

```console
$ pip uninstall cutadapt
```

then using my original conda environment, with cutadapt 1.18, again ran the commands in Python and got:

```python
> from cutadapt.__main__ import main
> main()
Run "cutadapt --help" to see command-line options.
See https://cutadapt.readthedocs.io/ for full documentation.

: error: Please give me something to do!
```
which is what I'd expect. Very strange!

**Comment by mikej888** [comment]
Removing `cutadapt` using `conda` then installing it in the current conda environment via `pip` installed version 3.4 which then ran without complaint:

```console
$ conda remove cutadapt
$ pip install cutadapt
$ cutadapt --version
3.4
```

The RiboViz workflow successfully ran.

**Comment by mikej888** [comment]
It might be an issue with the `cutadapt` conda package for 3.4 or for dependencies it relies upon.

**Comment by mikej888** [comment]
Added Troubleshooting, https://github.com/riboviz/riboviz/blob/develop/docs/user/prep-riboviz-run-nextflow.md#troubleshooting-cutadapt-3x-fails,

**Comment by mikej888** [comment]
This is not RiboViz-specific and a workaround is documented. Closing.
