### ISSUE TITLE
Flag for nextflow dsl 1

### ISSUE THREAD

**Issue by ewallace** [riboviz/RiboViz#466]
We need with high priority to add `nextflow.enable.dsl = 1` to the top of `prep_riboviz.nf`.

DSL2 is now the default for the latest release, so DSL1 pipelines won't run unless declared as such: https://www.nextflow.io/blog/2022/evolution-of-nextflow-runtime.html

**Comment by Maberuiz** [comment]
I've created a new branch called flag-dsl1-466. I'll include the line `nextflow.enable.dsl = 1` just before the line `import org.yaml.snakeyaml.Yaml` in the file `prep_riboviz.nf`. Then I'll try to run a full dataset (I have to run it anyway) with that new line included and check that everything works.

**Comment by Maberuiz** [comment]
When trying to run nextflow using the new file, an error rises saying that: `No such variable: enable`. The full nextflow.log can be seen in the next comment. When changing the line to `nextflow.enable.dsl = 2` to see if something happens, it seems like it reads that line even though it cannot read the variable enable. Therefore, the error this time turns to be:
`WARN: DSL 2 IS AN EXPERIMENTAL FEATURE UNDER DEVELOPMENT -- SYNTAX MAY CHANGE IN FUTURE RELEASE
No such variable: enable`
It seems to me that the line is not where it should be, however, I've tried moving it to lines 4, 14 or 306 and the problem persists. Another possible problem could be that we're using Nextflow version 20.04.1 and they're going to release version 22.04.0, so maybe the netflow.enable option was not implemented in the version we're using.
I think this must be a stupid error based on my low knowledge of workflow, but I haven't found any solution after all the trials and google searches, so if you could have a look @ewallace it would be great.

**Comment by Maberuiz** [comment]
The content of `.nextflow.log` is the following:

jun.-08 14:52:32.449 [main] DEBUG nextflow.cli.Launcher - $> nextflow run prep_riboviz.nf -params-file J-Sc_2014/Jan_2014_sec63_RPF_1-sample_CDS_w_250utrs_config_2-1.yaml -work-dir J-Sc_2014/work -ansi-log false --validate_only
jun.-08 14:52:32.740 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 20.04.1
jun.-08 14:52:32.772 [main] INFO  nextflow.cli.CmdRun - Launching `prep_riboviz.nf` [nauseous_perlman] - revision: 9eb7b85fcd
jun.-08 14:52:33.178 [main] DEBUG nextflow.Session - Session uuid: 0294b7a3-9ce0-4547-a61d-35c98e2aea6c
jun.-08 14:52:33.179 [main] DEBUG nextflow.Session - Run name: nauseous_perlman
jun.-08 14:52:33.180 [main] DEBUG nextflow.Session - Executor pool size: 4
jun.-08 14:52:33.242 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 20.04.1 build 5335
  Created: 03-05-2020 19:37 UTC (20:37 BST)
  System: Linux 3.10.0-1160.49.1.el7.x86_64
  Runtime: Groovy 2.5.8 on OpenJDK 64-Bit Server VM 11.0.1-internal+0-adhoc..src
  Encoding: UTF-8 (UTF-8)
  Process: 23417@node1h20.ecdf.ed.ac.uk [192.41.104.241]
  CPUs: 4 - Mem: 125.5 GB (109.1 GB) - Swap: 16 GB (16 GB)
jun.-08 14:52:33.294 [main] DEBUG nextflow.Session - Work-dir: /exports/eddie3_homes_local/s2255081/riboviz/riboviz/J-Sc_2014/work [gpfs]
jun.-08 14:52:33.294 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /exports/eddie3_homes_local/s2255081/riboviz/riboviz/bin
jun.-08 14:52:33.322 [main] DEBUG nextflow.Session - Observer factory: TowerFactory
jun.-08 14:52:33.326 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
jun.-08 14:52:33.533 [main] DEBUG nextflow.Session - Session start invoked
jun.-08 14:52:34.638 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
jun.-08 14:52:34.648 [main] DEBUG nextflow.Session - Workflow process names [dsl1]: countReads, cutAdapters, hisat2ORF, collateTpms, extractUmis, buildIndicesrRNA, bamToH5, createVizParamsConfigFile, renameTpms, trim5pMismatches, outputBams, demultiplex, cutAdaptersMultiplex, hisat2rRNA, makeBedgraphs, createInteractiveVizParamsConfigFile, generateStatsFigs, extractUmisMultiplex, samViewSort, buildIndicesORF, groupUmisPreDedup, groupUmisPostDedup, dedupUmis, staticHTML
jun.-08 14:52:34.650 [main] DEBUG nextflow.Session - Session aborted -- Cause: No such property: enable for class: nextflow.NextflowMeta
jun.-08 14:52:34.661 [main] ERROR nextflow.cli.Launcher - @unknown
groovy.lang.MissingPropertyException: No such property: enable for class: nextflow.NextflowMeta
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:65)
	at org.codehaus.groovy.runtime.callsite.GetEffectivePogoPropertySite.getProperty(GetEffectivePogoPropertySite.java:87)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:298)
	at Script_dc67b3cc.runScript(Script_dc67b3cc:4)
	at nextflow.script.BaseScript.runDsl1(BaseScript.groovy:153)
	at nextflow.script.BaseScript.run(BaseScript.groovy:189)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:225)
	at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:218)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:126)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:273)
	at nextflow.cli.Launcher.run(Launcher.groovy:460)
	at nextflow.cli.Launcher.main(Launcher.groovy:642)

**Comment by FlicAnderson** [comment]
I'd recommend for troubleshooting to try this to start with: 
> If you still want to continue to use DSL1 for your pipeline scripts [ ... ] use the command line option `-dsl1`. 
from https://www.nextflow.io/blog/2022/evolution-of-nextflow-runtime.html

**Comment by FlicAnderson** [comment]
Checking the nextflow code versions, I agree with @Maberuiz that this command probably didn't exist in the version of Nextflow we're using (**20.04.1**): 

From the tagged release version information: 
```
[Version 20.07.1](https://github.com/nextflow-io/nextflow/releases/tag/v20.07.1)

Add Dsl2 enable flag [https://github.com/nextflow-io/nextflow/commit/08238109450cc793e84f0612bcc70df16d8c92ce]
Add check on invalid scope syntax definition [https://github.com/nextflow-io/nextflow/commit/23c920212b99bbd6b12e6ff9bdac33e36b93435c]
Add channel as alias for Channel [https://github.com/nextflow-io/nextflow/commit/05c358c9dfbdbdbc2ba6131c74dcf7e3e3f3a3f0]
Add DSL2 deprecation + clean up syntax [https://github.com/nextflow-io/nextflow/commit/1b4b1307fd7a910f599098a143e1e6d4607ebdee]
```

This is the earliest mention I can find for the `nextflow.enable.dsl` command, so I think this explains why we get the error trying to include this line in `prep-riboviz.nf` (or also when trying `-dsl1` at the command line when attempting to run the vignette for example). 

This issue (riboviz/#466) is blocked, until we update the Nextflow version beyond at least **20.07**, and ideally to the latest version (currently **22.04.3**). 

We'll need to update installation documentation, check dependencies, and add the `nextflow.enable.dsl=1` line (or perhaps we could opt for adding the environment option fix `export NXF_DEFAULT_DSL=1` into `set-riboviz-env.sh` file?).
